package com.cyberswift.phe.dto;

public class IntakeRawWaterMainClass {

	private String CONSTRUCTION_OF_INTAKE_JETTY_DATE_OF_COMPLETION;

	private String CONSTRUCTION_OF_INTAKE_JETTY_DATE_OF_START;

	private String CONSTRUCTION_OF_INTAKE_JETTY_STATUS;

	private String CONSTRUCTION_OF_RAW_WATER_PUMP_HOUSE_DATE_OF_COMPLETION;

	private String CONSTRUCTION_OF_RAW_WATER_PUMP_HOUSE_DATE_OF_START;

	private String CONSTRUCTION_OF_RAW_WATER_PUMP_HOUSE_STATUS;

	private String CONSTRUCTION_OF_SUBSTATION_ELECTRICAL_DATE_OF_COMPLETION;

	private String CONSTRUCTION_OF_SUBSTATION_ELECTRICAL_DATE_OF_START;

	private String CONSTRUCTION_OF_SUBSTATION_ELECTRICAL_STATUS;

	private String CREATED_BY_ID;

	private String DISTRICT_ID;

	private String ID;

	private String INSTALLATION_OF_PUMPING_AND_ELECTRICAL_MACHINERY_DATE_OF_COMPLETION;

	private String INSTALLATION_OF_PUMPING_AND_ELECTRICAL_MACHINERY_DATE_OF_START;

	private String INSTALLATION_OF_PUMPING_AND_ELECTRICAL_MACHINERY_STATUS;

	private String LAYING_OF_RAW_WATER_DELIVERY_MAIN_DATE_OF_COMPLETION;

	private String LAYING_OF_RAW_WATER_DELIVERY_MAIN_DATE_OF_START;

	private String LAYING_OF_RAW_WATER_DELIVERY_MAIN_STATUS;

	private String LAYING_OF_SUCTION_MAIN_DATE_OF_COMPLETION;

	private String LAYING_OF_SUCTION_MAIN_DATE_OF_START;

	private String LAYING_OF_SUCTION_MAIN_STATUS;

	private String SCHEME_ID;

	private String SINKING_OF_PILE_FOR_INTAKE_JETTY_IFNO_DESCRIPTION;

	private String SINKING_OF_PILE_FOR_INTAKE_JETTY_ISDONE;

	public String getCONSTRUCTION_OF_INTAKE_JETTY_DATE_OF_COMPLETION() {
		return CONSTRUCTION_OF_INTAKE_JETTY_DATE_OF_COMPLETION;
	}

	public void setCONSTRUCTION_OF_INTAKE_JETTY_DATE_OF_COMPLETION(String cONSTRUCTION_OF_INTAKE_JETTY_DATE_OF_COMPLETION) {
		CONSTRUCTION_OF_INTAKE_JETTY_DATE_OF_COMPLETION = cONSTRUCTION_OF_INTAKE_JETTY_DATE_OF_COMPLETION;
	}

	public String getCONSTRUCTION_OF_INTAKE_JETTY_DATE_OF_START() {
		return CONSTRUCTION_OF_INTAKE_JETTY_DATE_OF_START;
	}

	public void setCONSTRUCTION_OF_INTAKE_JETTY_DATE_OF_START(String cONSTRUCTION_OF_INTAKE_JETTY_DATE_OF_START) {
		CONSTRUCTION_OF_INTAKE_JETTY_DATE_OF_START = cONSTRUCTION_OF_INTAKE_JETTY_DATE_OF_START;
	}

	public String getCONSTRUCTION_OF_INTAKE_JETTY_STATUS() {
		return CONSTRUCTION_OF_INTAKE_JETTY_STATUS;
	}

	public void setCONSTRUCTION_OF_INTAKE_JETTY_STATUS(String cONSTRUCTION_OF_INTAKE_JETTY_STATUS) {
		CONSTRUCTION_OF_INTAKE_JETTY_STATUS = cONSTRUCTION_OF_INTAKE_JETTY_STATUS;
	}

	public String getCONSTRUCTION_OF_RAW_WATER_PUMP_HOUSE_DATE_OF_COMPLETION() {
		return CONSTRUCTION_OF_RAW_WATER_PUMP_HOUSE_DATE_OF_COMPLETION;
	}

	public void setCONSTRUCTION_OF_RAW_WATER_PUMP_HOUSE_DATE_OF_COMPLETION(String cONSTRUCTION_OF_RAW_WATER_PUMP_HOUSE_DATE_OF_COMPLETION) {
		CONSTRUCTION_OF_RAW_WATER_PUMP_HOUSE_DATE_OF_COMPLETION = cONSTRUCTION_OF_RAW_WATER_PUMP_HOUSE_DATE_OF_COMPLETION;
	}

	public String getCONSTRUCTION_OF_RAW_WATER_PUMP_HOUSE_DATE_OF_START() {
		return CONSTRUCTION_OF_RAW_WATER_PUMP_HOUSE_DATE_OF_START;
	}

	public void setCONSTRUCTION_OF_RAW_WATER_PUMP_HOUSE_DATE_OF_START(String cONSTRUCTION_OF_RAW_WATER_PUMP_HOUSE_DATE_OF_START) {
		CONSTRUCTION_OF_RAW_WATER_PUMP_HOUSE_DATE_OF_START = cONSTRUCTION_OF_RAW_WATER_PUMP_HOUSE_DATE_OF_START;
	}

	public String getCONSTRUCTION_OF_RAW_WATER_PUMP_HOUSE_STATUS() {
		return CONSTRUCTION_OF_RAW_WATER_PUMP_HOUSE_STATUS;
	}

	public void setCONSTRUCTION_OF_RAW_WATER_PUMP_HOUSE_STATUS(String cONSTRUCTION_OF_RAW_WATER_PUMP_HOUSE_STATUS) {
		CONSTRUCTION_OF_RAW_WATER_PUMP_HOUSE_STATUS = cONSTRUCTION_OF_RAW_WATER_PUMP_HOUSE_STATUS;
	}

	public String getCONSTRUCTION_OF_SUBSTATION_ELECTRICAL_DATE_OF_COMPLETION() {
		return CONSTRUCTION_OF_SUBSTATION_ELECTRICAL_DATE_OF_COMPLETION;
	}

	public void setCONSTRUCTION_OF_SUBSTATION_ELECTRICAL_DATE_OF_COMPLETION(String cONSTRUCTION_OF_SUBSTATION_ELECTRICAL_DATE_OF_COMPLETION) {
		CONSTRUCTION_OF_SUBSTATION_ELECTRICAL_DATE_OF_COMPLETION = cONSTRUCTION_OF_SUBSTATION_ELECTRICAL_DATE_OF_COMPLETION;
	}

	public String getCONSTRUCTION_OF_SUBSTATION_ELECTRICAL_DATE_OF_START() {
		return CONSTRUCTION_OF_SUBSTATION_ELECTRICAL_DATE_OF_START;
	}

	public void setCONSTRUCTION_OF_SUBSTATION_ELECTRICAL_DATE_OF_START(String cONSTRUCTION_OF_SUBSTATION_ELECTRICAL_DATE_OF_START) {
		CONSTRUCTION_OF_SUBSTATION_ELECTRICAL_DATE_OF_START = cONSTRUCTION_OF_SUBSTATION_ELECTRICAL_DATE_OF_START;
	}

	public String getCONSTRUCTION_OF_SUBSTATION_ELECTRICAL_STATUS() {
		return CONSTRUCTION_OF_SUBSTATION_ELECTRICAL_STATUS;
	}

	public void setCONSTRUCTION_OF_SUBSTATION_ELECTRICAL_STATUS(String cONSTRUCTION_OF_SUBSTATION_ELECTRICAL_STATUS) {
		CONSTRUCTION_OF_SUBSTATION_ELECTRICAL_STATUS = cONSTRUCTION_OF_SUBSTATION_ELECTRICAL_STATUS;
	}

	public String getCREATED_BY_ID() {
		return CREATED_BY_ID;
	}

	public void setCREATED_BY_ID(String cREATED_BY_ID) {
		CREATED_BY_ID = cREATED_BY_ID;
	}

	public String getDISTRICT_ID() {
		return DISTRICT_ID;
	}

	public void setDISTRICT_ID(String dISTRICT_ID) {
		DISTRICT_ID = dISTRICT_ID;
	}

	public String getID() {
		return ID;
	}

	public void setID(String iD) {
		ID = iD;
	}

	public String getINSTALLATION_OF_PUMPING_AND_ELECTRICAL_MACHINERY_DATE_OF_COMPLETION() {
		return INSTALLATION_OF_PUMPING_AND_ELECTRICAL_MACHINERY_DATE_OF_COMPLETION;
	}

	public void setINSTALLATION_OF_PUMPING_AND_ELECTRICAL_MACHINERY_DATE_OF_COMPLETION(
			String iNSTALLATION_OF_PUMPING_AND_ELECTRICAL_MACHINERY_DATE_OF_COMPLETION) {
		INSTALLATION_OF_PUMPING_AND_ELECTRICAL_MACHINERY_DATE_OF_COMPLETION = iNSTALLATION_OF_PUMPING_AND_ELECTRICAL_MACHINERY_DATE_OF_COMPLETION;
	}

	public String getINSTALLATION_OF_PUMPING_AND_ELECTRICAL_MACHINERY_DATE_OF_START() {
		return INSTALLATION_OF_PUMPING_AND_ELECTRICAL_MACHINERY_DATE_OF_START;
	}

	public void setINSTALLATION_OF_PUMPING_AND_ELECTRICAL_MACHINERY_DATE_OF_START(String iNSTALLATION_OF_PUMPING_AND_ELECTRICAL_MACHINERY_DATE_OF_START) {
		INSTALLATION_OF_PUMPING_AND_ELECTRICAL_MACHINERY_DATE_OF_START = iNSTALLATION_OF_PUMPING_AND_ELECTRICAL_MACHINERY_DATE_OF_START;
	}

	public String getINSTALLATION_OF_PUMPING_AND_ELECTRICAL_MACHINERY_STATUS() {
		return INSTALLATION_OF_PUMPING_AND_ELECTRICAL_MACHINERY_STATUS;
	}

	public void setINSTALLATION_OF_PUMPING_AND_ELECTRICAL_MACHINERY_STATUS(String iNSTALLATION_OF_PUMPING_AND_ELECTRICAL_MACHINERY_STATUS) {
		INSTALLATION_OF_PUMPING_AND_ELECTRICAL_MACHINERY_STATUS = iNSTALLATION_OF_PUMPING_AND_ELECTRICAL_MACHINERY_STATUS;
	}

	public String getLAYING_OF_RAW_WATER_DELIVERY_MAIN_DATE_OF_COMPLETION() {
		return LAYING_OF_RAW_WATER_DELIVERY_MAIN_DATE_OF_COMPLETION;
	}

	public void setLAYING_OF_RAW_WATER_DELIVERY_MAIN_DATE_OF_COMPLETION(String lAYING_OF_RAW_WATER_DELIVERY_MAIN_DATE_OF_COMPLETION) {
		LAYING_OF_RAW_WATER_DELIVERY_MAIN_DATE_OF_COMPLETION = lAYING_OF_RAW_WATER_DELIVERY_MAIN_DATE_OF_COMPLETION;
	}

	public String getLAYING_OF_RAW_WATER_DELIVERY_MAIN_DATE_OF_START() {
		return LAYING_OF_RAW_WATER_DELIVERY_MAIN_DATE_OF_START;
	}

	public void setLAYING_OF_RAW_WATER_DELIVERY_MAIN_DATE_OF_START(String lAYING_OF_RAW_WATER_DELIVERY_MAIN_DATE_OF_START) {
		LAYING_OF_RAW_WATER_DELIVERY_MAIN_DATE_OF_START = lAYING_OF_RAW_WATER_DELIVERY_MAIN_DATE_OF_START;
	}

	public String getLAYING_OF_RAW_WATER_DELIVERY_MAIN_STATUS() {
		return LAYING_OF_RAW_WATER_DELIVERY_MAIN_STATUS;
	}

	public void setLAYING_OF_RAW_WATER_DELIVERY_MAIN_STATUS(String lAYING_OF_RAW_WATER_DELIVERY_MAIN_STATUS) {
		LAYING_OF_RAW_WATER_DELIVERY_MAIN_STATUS = lAYING_OF_RAW_WATER_DELIVERY_MAIN_STATUS;
	}

	public String getLAYING_OF_SUCTION_MAIN_DATE_OF_COMPLETION() {
		return LAYING_OF_SUCTION_MAIN_DATE_OF_COMPLETION;
	}

	public void setLAYING_OF_SUCTION_MAIN_DATE_OF_COMPLETION(String lAYING_OF_SUCTION_MAIN_DATE_OF_COMPLETION) {
		LAYING_OF_SUCTION_MAIN_DATE_OF_COMPLETION = lAYING_OF_SUCTION_MAIN_DATE_OF_COMPLETION;
	}

	public String getLAYING_OF_SUCTION_MAIN_DATE_OF_START() {
		return LAYING_OF_SUCTION_MAIN_DATE_OF_START;
	}

	public void setLAYING_OF_SUCTION_MAIN_DATE_OF_START(String lAYING_OF_SUCTION_MAIN_DATE_OF_START) {
		LAYING_OF_SUCTION_MAIN_DATE_OF_START = lAYING_OF_SUCTION_MAIN_DATE_OF_START;
	}

	public String getLAYING_OF_SUCTION_MAIN_STATUS() {
		return LAYING_OF_SUCTION_MAIN_STATUS;
	}

	public void setLAYING_OF_SUCTION_MAIN_STATUS(String lAYING_OF_SUCTION_MAIN_STATUS) {
		LAYING_OF_SUCTION_MAIN_STATUS = lAYING_OF_SUCTION_MAIN_STATUS;
	}

	public String getSCHEME_ID() {
		return SCHEME_ID;
	}

	public void setSCHEME_ID(String sCHEME_ID) {
		SCHEME_ID = sCHEME_ID;
	}

	public String getSINKING_OF_PILE_FOR_INTAKE_JETTY_IFNO_DESCRIPTION() {
		return SINKING_OF_PILE_FOR_INTAKE_JETTY_IFNO_DESCRIPTION;
	}

	public void setSINKING_OF_PILE_FOR_INTAKE_JETTY_IFNO_DESCRIPTION(String sINKING_OF_PILE_FOR_INTAKE_JETTY_IFNO_DESCRIPTION) {
		SINKING_OF_PILE_FOR_INTAKE_JETTY_IFNO_DESCRIPTION = sINKING_OF_PILE_FOR_INTAKE_JETTY_IFNO_DESCRIPTION;
	}

	public String getSINKING_OF_PILE_FOR_INTAKE_JETTY_ISDONE() {
		return SINKING_OF_PILE_FOR_INTAKE_JETTY_ISDONE;
	}

	public void setSINKING_OF_PILE_FOR_INTAKE_JETTY_ISDONE(String sINKING_OF_PILE_FOR_INTAKE_JETTY_ISDONE) {
		SINKING_OF_PILE_FOR_INTAKE_JETTY_ISDONE = sINKING_OF_PILE_FOR_INTAKE_JETTY_ISDONE;
	}

}
