package com.cyberswift.phe.dto;

public class LandAcquisitionClass {

	private String COMMENCEMENT_DESCRIPTION;

	private String COMMENCEMENT_ISDONE;

	private String CREATED_BY_ID;

	private String DATE_OF_ACQUISITION;

	private String DISTRICT_ID;

	private String HINDRANCES_ISDONE;

	private String HINDRANCES_DESCRIPTION;

	private String ID;

	private String IDENTIFICATION_DESCRIPTION;

	private String IDENTIFICATION_ISDONE;

	private String SCHEME_ID;

	public String getCOMMENCEMENT_DESCRIPTION() {
		return COMMENCEMENT_DESCRIPTION;
	}

	public void setCOMMENCEMENT_DESCRIPTION(String cOMMENCEMENT_DESCRIPTION) {
		COMMENCEMENT_DESCRIPTION = cOMMENCEMENT_DESCRIPTION;
	}

	public String getCOMMENCEMENT_ISDONE() {
		return COMMENCEMENT_ISDONE;
	}

	public void setCOMMENCEMENT_ISDONE(String cOMMENCEMENT_ISDONE) {
		COMMENCEMENT_ISDONE = cOMMENCEMENT_ISDONE;
	}

	public String getCREATED_BY_ID() {
		return CREATED_BY_ID;
	}

	public void setCREATED_BY_ID(String cREATED_BY_ID) {
		CREATED_BY_ID = cREATED_BY_ID;
	}

	public String getDATE_OF_ACQUISITION() {
		return DATE_OF_ACQUISITION;
	}

	public void setDATE_OF_ACQUISITION(String dATE_OF_ACQUISITION) {
		DATE_OF_ACQUISITION = dATE_OF_ACQUISITION;
	}

	public String getDISTRICT_ID() {
		return DISTRICT_ID;
	}

	public void setDISTRICT_ID(String dISTRICT_ID) {
		DISTRICT_ID = dISTRICT_ID;
	}

	public String getHINDRANCES_ISDONE() {
		return HINDRANCES_ISDONE;
	}

	public void setHINDRANCES_ISDONE(String hINDRANCES_ISDONE) {
		HINDRANCES_ISDONE = hINDRANCES_ISDONE;
	}

	public String getHINDRANCES_DESCRIPTION() {
		return HINDRANCES_DESCRIPTION;
	}

	public void setHINDRANCES_DESCRIPTION(String hINDRANCES_DESCRIPTION) {
		HINDRANCES_DESCRIPTION = hINDRANCES_DESCRIPTION;
	}

	public String getID() {
		return ID;
	}

	public void setID(String iD) {
		ID = iD;
	}

	public String getIDENTIFICATION_DESCRIPTION() {
		return IDENTIFICATION_DESCRIPTION;
	}

	public void setIDENTIFICATION_DESCRIPTION(String iDENTIFICATION_DESCRIPTION) {
		IDENTIFICATION_DESCRIPTION = iDENTIFICATION_DESCRIPTION;
	}

	public String getIDENTIFICATION_ISDONE() {
		return IDENTIFICATION_ISDONE;
	}

	public void setIDENTIFICATION_ISDONE(String iDENTIFICATION_ISDONE) {
		IDENTIFICATION_ISDONE = iDENTIFICATION_ISDONE;
	}

	public String getSCHEME_ID() {
		return SCHEME_ID;
	}

	public void setSCHEME_ID(String sCHEME_ID) {
		SCHEME_ID = sCHEME_ID;
	}

}
