package com.cyberswift.phe.dto;

public class LayingClearWaterClass {

	private String CONSTRUCTION_OF_BOOSTING_STATION_DATE_OF_COMPLETION;

	private String CONSTRUCTION_OF_BOOSTING_STATION_DATE_OF_START;

	private String CONSTRUCTION_OF_BOOSTING_STATION_STATUS;

	private String CONSTRUCTION_OF_ZONAL_OH_RESERVOIR_ZONAL_HEAD_WORK_SITE_DATE_OF_COMPLETION;

	private String CONSTRUCTION_OF_ZONAL_OH_RESERVOIR_ZONAL_HEAD_WORK_SITE_DATE_OF_START;

	private String CONSTRUCTION_OF_ZONAL_OH_RESERVOIR_ZONAL_HEAD_WORK_SITE_STATUS;

	private String CREATED_BY_ID;

	private String DISTRICT_ID;

	private String ID;

	private String SCHEME_ID;

	public String getCONSTRUCTION_OF_BOOSTING_STATION_DATE_OF_COMPLETION() {
		return CONSTRUCTION_OF_BOOSTING_STATION_DATE_OF_COMPLETION;
	}

	public void setCONSTRUCTION_OF_BOOSTING_STATION_DATE_OF_COMPLETION(String cONSTRUCTION_OF_BOOSTING_STATION_DATE_OF_COMPLETION) {
		CONSTRUCTION_OF_BOOSTING_STATION_DATE_OF_COMPLETION = cONSTRUCTION_OF_BOOSTING_STATION_DATE_OF_COMPLETION;
	}

	public String getCONSTRUCTION_OF_BOOSTING_STATION_DATE_OF_START() {
		return CONSTRUCTION_OF_BOOSTING_STATION_DATE_OF_START;
	}

	public void setCONSTRUCTION_OF_BOOSTING_STATION_DATE_OF_START(String cONSTRUCTION_OF_BOOSTING_STATION_DATE_OF_START) {
		CONSTRUCTION_OF_BOOSTING_STATION_DATE_OF_START = cONSTRUCTION_OF_BOOSTING_STATION_DATE_OF_START;
	}

	public String getCONSTRUCTION_OF_BOOSTING_STATION_STATUS() {
		return CONSTRUCTION_OF_BOOSTING_STATION_STATUS;
	}

	public void setCONSTRUCTION_OF_BOOSTING_STATION_STATUS(String cONSTRUCTION_OF_BOOSTING_STATION_STATUS) {
		CONSTRUCTION_OF_BOOSTING_STATION_STATUS = cONSTRUCTION_OF_BOOSTING_STATION_STATUS;
	}

	public String getCONSTRUCTION_OF_ZONAL_OH_RESERVOIR_ZONAL_HEAD_WORK_SITE_DATE_OF_COMPLETION() {
		return CONSTRUCTION_OF_ZONAL_OH_RESERVOIR_ZONAL_HEAD_WORK_SITE_DATE_OF_COMPLETION;
	}

	public void setCONSTRUCTION_OF_ZONAL_OH_RESERVOIR_ZONAL_HEAD_WORK_SITE_DATE_OF_COMPLETION(
			String cONSTRUCTION_OF_ZONAL_OH_RESERVOIR_ZONAL_HEAD_WORK_SITE_DATE_OF_COMPLETION) {
		CONSTRUCTION_OF_ZONAL_OH_RESERVOIR_ZONAL_HEAD_WORK_SITE_DATE_OF_COMPLETION = cONSTRUCTION_OF_ZONAL_OH_RESERVOIR_ZONAL_HEAD_WORK_SITE_DATE_OF_COMPLETION;
	}

	public String getCONSTRUCTION_OF_ZONAL_OH_RESERVOIR_ZONAL_HEAD_WORK_SITE_DATE_OF_START() {
		return CONSTRUCTION_OF_ZONAL_OH_RESERVOIR_ZONAL_HEAD_WORK_SITE_DATE_OF_START;
	}

	public void setCONSTRUCTION_OF_ZONAL_OH_RESERVOIR_ZONAL_HEAD_WORK_SITE_DATE_OF_START(
			String cONSTRUCTION_OF_ZONAL_OH_RESERVOIR_ZONAL_HEAD_WORK_SITE_DATE_OF_START) {
		CONSTRUCTION_OF_ZONAL_OH_RESERVOIR_ZONAL_HEAD_WORK_SITE_DATE_OF_START = cONSTRUCTION_OF_ZONAL_OH_RESERVOIR_ZONAL_HEAD_WORK_SITE_DATE_OF_START;
	}

	public String getCONSTRUCTION_OF_ZONAL_OH_RESERVOIR_ZONAL_HEAD_WORK_SITE_STATUS() {
		return CONSTRUCTION_OF_ZONAL_OH_RESERVOIR_ZONAL_HEAD_WORK_SITE_STATUS;
	}

	public void setCONSTRUCTION_OF_ZONAL_OH_RESERVOIR_ZONAL_HEAD_WORK_SITE_STATUS(String cONSTRUCTION_OF_ZONAL_OH_RESERVOIR_ZONAL_HEAD_WORK_SITE_STATUS) {
		CONSTRUCTION_OF_ZONAL_OH_RESERVOIR_ZONAL_HEAD_WORK_SITE_STATUS = cONSTRUCTION_OF_ZONAL_OH_RESERVOIR_ZONAL_HEAD_WORK_SITE_STATUS;
	}

	public String getCREATED_BY_ID() {
		return CREATED_BY_ID;
	}

	public void setCREATED_BY_ID(String cREATED_BY_ID) {
		CREATED_BY_ID = cREATED_BY_ID;
	}

	public String getDISTRICT_ID() {
		return DISTRICT_ID;
	}

	public void setDISTRICT_ID(String dISTRICT_ID) {
		DISTRICT_ID = dISTRICT_ID;
	}

	public String getID() {
		return ID;
	}

	public void setID(String iD) {
		ID = iD;
	}

	public String getSCHEME_ID() {
		return SCHEME_ID;
	}

	public void setSCHEME_ID(String sCHEME_ID) {
		SCHEME_ID = sCHEME_ID;
	}

}
