package com.cyberswift.phe.dto;

public class WaterTreatementClass {

	private String CONSTRUCTION_OF_CHEMICAL_HOUSE_DATE_OF_COMPLETION;

	private String CONSTRUCTION_OF_CHEMICAL_HOUSE_DATE_OF_START;

	private String CONSTRUCTION_OF_CHEMICAL_HOUSE_STATUS;

	private String CONSTRUCTION_OF_CHLORINE_ROOM_AND_INSTALLATION_OF_CHLORINATION_ARRANGEMENT_DATE_OF_START;

	private String CONSTRUCTION_OF_CHLORINE_ROOM_AND_INSTALLATION_OF_CHLORINATION_ARRANGEMENT_STATUS;

	private String CONSTRUCTION_OF_CHLORINE_ROOM_DATE_OF_COMPLETION;

	private String CONSTRUCTION_OF_CLARIFLOCCULATOR_DATE_OF_COMPLETION;

	private String CONSTRUCTION_OF_CLARIFLOCCULATOR_OR_PLATE_SETTLER_OR_TUBE_SETTLER_DATE_OF_START;

	private String CONSTRUCTION_OF_CLARIFLOCCULATOR_OR_PLATE_SETTLER_OR_TUBE_SETTLER_STATUS;

	private String CONSTRUCTION_OF_CLEAR_WATER_PUMP_HOUSE_DATE_OF_COMPLETION;

	private String CONSTRUCTION_OF_CLEAR_WATER_PUMP_HOUSE_DATE_OF_START;

	private String CONSTRUCTION_OF_CLEAR_WATER_PUMP_HOUSE_STATUS;

	private String CONSTRUCTION_OF_FLUSH_MIXTURE_DATE_OF_COMPLETION;

	private String CONSTRUCTION_OF_FLUSH_MIXTURE_DATE_OF_START;

	private String CONSTRUCTION_OF_FLUSH_MIXTURE_STATUS;

	private String CONSTRUCTION_OF_INTAKE_WELL_DATE_OF_COMPLETION;

	private String CONSTRUCTION_OF_INTAKE_WELL_DATE_OF_START;

	private String CONSTRUCTION_OF_INTAKE_WELL_STATUS;

	private String CONSTRUCTION_OF_RAPID_SAND_FILTER_DATE_OF_COMPLETION;

	private String CONSTRUCTION_OF_RAPID_SAND_FILTER_DATE_OF_START;

	private String CONSTRUCTION_OF_RAPID_SAND_FILTER_STATUS;

	private String CREATED_BY_ID;

	private String DISTRICT_ID;

	private String ID;

	private String INSTALLATION_OF_ELECTRICAL_AND_MECHANICAL_MACHINERY_DATE_OF_COMPLETION;

	private String INSTALLATION_OF_ELECTRICAL_AND_MECHANICAL_MACHINERY_DATE_OF_START;

	private String INSTALLATION_OF_ELECTRICAL_AND_MECHANICAL_MACHINERY_STATUS;

	private String SCHEME_ID;

	public String getCONSTRUCTION_OF_CHEMICAL_HOUSE_DATE_OF_COMPLETION() {
		return CONSTRUCTION_OF_CHEMICAL_HOUSE_DATE_OF_COMPLETION;
	}

	public void setCONSTRUCTION_OF_CHEMICAL_HOUSE_DATE_OF_COMPLETION(String cONSTRUCTION_OF_CHEMICAL_HOUSE_DATE_OF_COMPLETION) {
		CONSTRUCTION_OF_CHEMICAL_HOUSE_DATE_OF_COMPLETION = cONSTRUCTION_OF_CHEMICAL_HOUSE_DATE_OF_COMPLETION;
	}

	public String getCONSTRUCTION_OF_CHEMICAL_HOUSE_DATE_OF_START() {
		return CONSTRUCTION_OF_CHEMICAL_HOUSE_DATE_OF_START;
	}

	public void setCONSTRUCTION_OF_CHEMICAL_HOUSE_DATE_OF_START(String cONSTRUCTION_OF_CHEMICAL_HOUSE_DATE_OF_START) {
		CONSTRUCTION_OF_CHEMICAL_HOUSE_DATE_OF_START = cONSTRUCTION_OF_CHEMICAL_HOUSE_DATE_OF_START;
	}

	public String getCONSTRUCTION_OF_CHEMICAL_HOUSE_STATUS() {
		return CONSTRUCTION_OF_CHEMICAL_HOUSE_STATUS;
	}

	public void setCONSTRUCTION_OF_CHEMICAL_HOUSE_STATUS(String cONSTRUCTION_OF_CHEMICAL_HOUSE_STATUS) {
		CONSTRUCTION_OF_CHEMICAL_HOUSE_STATUS = cONSTRUCTION_OF_CHEMICAL_HOUSE_STATUS;
	}

	public String getCONSTRUCTION_OF_CHLORINE_ROOM_AND_INSTALLATION_OF_CHLORINATION_ARRANGEMENT_DATE_OF_START() {
		return CONSTRUCTION_OF_CHLORINE_ROOM_AND_INSTALLATION_OF_CHLORINATION_ARRANGEMENT_DATE_OF_START;
	}

	public void setCONSTRUCTION_OF_CHLORINE_ROOM_AND_INSTALLATION_OF_CHLORINATION_ARRANGEMENT_DATE_OF_START(
			String cONSTRUCTION_OF_CHLORINE_ROOM_AND_INSTALLATION_OF_CHLORINATION_ARRANGEMENT_DATE_OF_START) {
		CONSTRUCTION_OF_CHLORINE_ROOM_AND_INSTALLATION_OF_CHLORINATION_ARRANGEMENT_DATE_OF_START = cONSTRUCTION_OF_CHLORINE_ROOM_AND_INSTALLATION_OF_CHLORINATION_ARRANGEMENT_DATE_OF_START;
	}

	public String getCONSTRUCTION_OF_CHLORINE_ROOM_AND_INSTALLATION_OF_CHLORINATION_ARRANGEMENT_STATUS() {
		return CONSTRUCTION_OF_CHLORINE_ROOM_AND_INSTALLATION_OF_CHLORINATION_ARRANGEMENT_STATUS;
	}

	public void setCONSTRUCTION_OF_CHLORINE_ROOM_AND_INSTALLATION_OF_CHLORINATION_ARRANGEMENT_STATUS(
			String cONSTRUCTION_OF_CHLORINE_ROOM_AND_INSTALLATION_OF_CHLORINATION_ARRANGEMENT_STATUS) {
		CONSTRUCTION_OF_CHLORINE_ROOM_AND_INSTALLATION_OF_CHLORINATION_ARRANGEMENT_STATUS = cONSTRUCTION_OF_CHLORINE_ROOM_AND_INSTALLATION_OF_CHLORINATION_ARRANGEMENT_STATUS;
	}

	public String getCONSTRUCTION_OF_CHLORINE_ROOM_DATE_OF_COMPLETION() {
		return CONSTRUCTION_OF_CHLORINE_ROOM_DATE_OF_COMPLETION;
	}

	public void setCONSTRUCTION_OF_CHLORINE_ROOM_DATE_OF_COMPLETION(String cONSTRUCTION_OF_CHLORINE_ROOM_DATE_OF_COMPLETION) {
		CONSTRUCTION_OF_CHLORINE_ROOM_DATE_OF_COMPLETION = cONSTRUCTION_OF_CHLORINE_ROOM_DATE_OF_COMPLETION;
	}

	public String getCONSTRUCTION_OF_CLARIFLOCCULATOR_DATE_OF_COMPLETION() {
		return CONSTRUCTION_OF_CLARIFLOCCULATOR_DATE_OF_COMPLETION;
	}

	public void setCONSTRUCTION_OF_CLARIFLOCCULATOR_DATE_OF_COMPLETION(String cONSTRUCTION_OF_CLARIFLOCCULATOR_DATE_OF_COMPLETION) {
		CONSTRUCTION_OF_CLARIFLOCCULATOR_DATE_OF_COMPLETION = cONSTRUCTION_OF_CLARIFLOCCULATOR_DATE_OF_COMPLETION;
	}

	public String getCONSTRUCTION_OF_CLARIFLOCCULATOR_OR_PLATE_SETTLER_OR_TUBE_SETTLER_DATE_OF_START() {
		return CONSTRUCTION_OF_CLARIFLOCCULATOR_OR_PLATE_SETTLER_OR_TUBE_SETTLER_DATE_OF_START;
	}

	public void setCONSTRUCTION_OF_CLARIFLOCCULATOR_OR_PLATE_SETTLER_OR_TUBE_SETTLER_DATE_OF_START(
			String cONSTRUCTION_OF_CLARIFLOCCULATOR_OR_PLATE_SETTLER_OR_TUBE_SETTLER_DATE_OF_START) {
		CONSTRUCTION_OF_CLARIFLOCCULATOR_OR_PLATE_SETTLER_OR_TUBE_SETTLER_DATE_OF_START = cONSTRUCTION_OF_CLARIFLOCCULATOR_OR_PLATE_SETTLER_OR_TUBE_SETTLER_DATE_OF_START;
	}

	public String getCONSTRUCTION_OF_CLARIFLOCCULATOR_OR_PLATE_SETTLER_OR_TUBE_SETTLER_STATUS() {
		return CONSTRUCTION_OF_CLARIFLOCCULATOR_OR_PLATE_SETTLER_OR_TUBE_SETTLER_STATUS;
	}

	public void setCONSTRUCTION_OF_CLARIFLOCCULATOR_OR_PLATE_SETTLER_OR_TUBE_SETTLER_STATUS(
			String cONSTRUCTION_OF_CLARIFLOCCULATOR_OR_PLATE_SETTLER_OR_TUBE_SETTLER_STATUS) {
		CONSTRUCTION_OF_CLARIFLOCCULATOR_OR_PLATE_SETTLER_OR_TUBE_SETTLER_STATUS = cONSTRUCTION_OF_CLARIFLOCCULATOR_OR_PLATE_SETTLER_OR_TUBE_SETTLER_STATUS;
	}

	public String getCONSTRUCTION_OF_CLEAR_WATER_PUMP_HOUSE_DATE_OF_COMPLETION() {
		return CONSTRUCTION_OF_CLEAR_WATER_PUMP_HOUSE_DATE_OF_COMPLETION;
	}

	public void setCONSTRUCTION_OF_CLEAR_WATER_PUMP_HOUSE_DATE_OF_COMPLETION(String cONSTRUCTION_OF_CLEAR_WATER_PUMP_HOUSE_DATE_OF_COMPLETION) {
		CONSTRUCTION_OF_CLEAR_WATER_PUMP_HOUSE_DATE_OF_COMPLETION = cONSTRUCTION_OF_CLEAR_WATER_PUMP_HOUSE_DATE_OF_COMPLETION;
	}

	public String getCONSTRUCTION_OF_CLEAR_WATER_PUMP_HOUSE_DATE_OF_START() {
		return CONSTRUCTION_OF_CLEAR_WATER_PUMP_HOUSE_DATE_OF_START;
	}

	public void setCONSTRUCTION_OF_CLEAR_WATER_PUMP_HOUSE_DATE_OF_START(String cONSTRUCTION_OF_CLEAR_WATER_PUMP_HOUSE_DATE_OF_START) {
		CONSTRUCTION_OF_CLEAR_WATER_PUMP_HOUSE_DATE_OF_START = cONSTRUCTION_OF_CLEAR_WATER_PUMP_HOUSE_DATE_OF_START;
	}

	public String getCONSTRUCTION_OF_CLEAR_WATER_PUMP_HOUSE_STATUS() {
		return CONSTRUCTION_OF_CLEAR_WATER_PUMP_HOUSE_STATUS;
	}

	public void setCONSTRUCTION_OF_CLEAR_WATER_PUMP_HOUSE_STATUS(String cONSTRUCTION_OF_CLEAR_WATER_PUMP_HOUSE_STATUS) {
		CONSTRUCTION_OF_CLEAR_WATER_PUMP_HOUSE_STATUS = cONSTRUCTION_OF_CLEAR_WATER_PUMP_HOUSE_STATUS;
	}

	public String getCONSTRUCTION_OF_FLUSH_MIXTURE_DATE_OF_COMPLETION() {
		return CONSTRUCTION_OF_FLUSH_MIXTURE_DATE_OF_COMPLETION;
	}

	public void setCONSTRUCTION_OF_FLUSH_MIXTURE_DATE_OF_COMPLETION(String cONSTRUCTION_OF_FLUSH_MIXTURE_DATE_OF_COMPLETION) {
		CONSTRUCTION_OF_FLUSH_MIXTURE_DATE_OF_COMPLETION = cONSTRUCTION_OF_FLUSH_MIXTURE_DATE_OF_COMPLETION;
	}

	public String getCONSTRUCTION_OF_FLUSH_MIXTURE_DATE_OF_START() {
		return CONSTRUCTION_OF_FLUSH_MIXTURE_DATE_OF_START;
	}

	public void setCONSTRUCTION_OF_FLUSH_MIXTURE_DATE_OF_START(String cONSTRUCTION_OF_FLUSH_MIXTURE_DATE_OF_START) {
		CONSTRUCTION_OF_FLUSH_MIXTURE_DATE_OF_START = cONSTRUCTION_OF_FLUSH_MIXTURE_DATE_OF_START;
	}

	public String getCONSTRUCTION_OF_FLUSH_MIXTURE_STATUS() {
		return CONSTRUCTION_OF_FLUSH_MIXTURE_STATUS;
	}

	public void setCONSTRUCTION_OF_FLUSH_MIXTURE_STATUS(String cONSTRUCTION_OF_FLUSH_MIXTURE_STATUS) {
		CONSTRUCTION_OF_FLUSH_MIXTURE_STATUS = cONSTRUCTION_OF_FLUSH_MIXTURE_STATUS;
	}

	public String getCONSTRUCTION_OF_INTAKE_WELL_DATE_OF_COMPLETION() {
		return CONSTRUCTION_OF_INTAKE_WELL_DATE_OF_COMPLETION;
	}

	public void setCONSTRUCTION_OF_INTAKE_WELL_DATE_OF_COMPLETION(String cONSTRUCTION_OF_INTAKE_WELL_DATE_OF_COMPLETION) {
		CONSTRUCTION_OF_INTAKE_WELL_DATE_OF_COMPLETION = cONSTRUCTION_OF_INTAKE_WELL_DATE_OF_COMPLETION;
	}

	public String getCONSTRUCTION_OF_INTAKE_WELL_DATE_OF_START() {
		return CONSTRUCTION_OF_INTAKE_WELL_DATE_OF_START;
	}

	public void setCONSTRUCTION_OF_INTAKE_WELL_DATE_OF_START(String cONSTRUCTION_OF_INTAKE_WELL_DATE_OF_START) {
		CONSTRUCTION_OF_INTAKE_WELL_DATE_OF_START = cONSTRUCTION_OF_INTAKE_WELL_DATE_OF_START;
	}

	public String getCONSTRUCTION_OF_INTAKE_WELL_STATUS() {
		return CONSTRUCTION_OF_INTAKE_WELL_STATUS;
	}

	public void setCONSTRUCTION_OF_INTAKE_WELL_STATUS(String cONSTRUCTION_OF_INTAKE_WELL_STATUS) {
		CONSTRUCTION_OF_INTAKE_WELL_STATUS = cONSTRUCTION_OF_INTAKE_WELL_STATUS;
	}

	public String getCONSTRUCTION_OF_RAPID_SAND_FILTER_DATE_OF_COMPLETION() {
		return CONSTRUCTION_OF_RAPID_SAND_FILTER_DATE_OF_COMPLETION;
	}

	public void setCONSTRUCTION_OF_RAPID_SAND_FILTER_DATE_OF_COMPLETION(String cONSTRUCTION_OF_RAPID_SAND_FILTER_DATE_OF_COMPLETION) {
		CONSTRUCTION_OF_RAPID_SAND_FILTER_DATE_OF_COMPLETION = cONSTRUCTION_OF_RAPID_SAND_FILTER_DATE_OF_COMPLETION;
	}

	public String getCONSTRUCTION_OF_RAPID_SAND_FILTER_DATE_OF_START() {
		return CONSTRUCTION_OF_RAPID_SAND_FILTER_DATE_OF_START;
	}

	public void setCONSTRUCTION_OF_RAPID_SAND_FILTER_DATE_OF_START(String cONSTRUCTION_OF_RAPID_SAND_FILTER_DATE_OF_START) {
		CONSTRUCTION_OF_RAPID_SAND_FILTER_DATE_OF_START = cONSTRUCTION_OF_RAPID_SAND_FILTER_DATE_OF_START;
	}

	public String getCONSTRUCTION_OF_RAPID_SAND_FILTER_STATUS() {
		return CONSTRUCTION_OF_RAPID_SAND_FILTER_STATUS;
	}

	public void setCONSTRUCTION_OF_RAPID_SAND_FILTER_STATUS(String cONSTRUCTION_OF_RAPID_SAND_FILTER_STATUS) {
		CONSTRUCTION_OF_RAPID_SAND_FILTER_STATUS = cONSTRUCTION_OF_RAPID_SAND_FILTER_STATUS;
	}

	public String getCREATED_BY_ID() {
		return CREATED_BY_ID;
	}

	public void setCREATED_BY_ID(String cREATED_BY_ID) {
		CREATED_BY_ID = cREATED_BY_ID;
	}

	public String getDISTRICT_ID() {
		return DISTRICT_ID;
	}

	public void setDISTRICT_ID(String dISTRICT_ID) {
		DISTRICT_ID = dISTRICT_ID;
	}

	public String getID() {
		return ID;
	}

	public void setID(String iD) {
		ID = iD;
	}

	public String getINSTALLATION_OF_ELECTRICAL_AND_MECHANICAL_MACHINERY_DATE_OF_COMPLETION() {
		return INSTALLATION_OF_ELECTRICAL_AND_MECHANICAL_MACHINERY_DATE_OF_COMPLETION;
	}

	public void setINSTALLATION_OF_ELECTRICAL_AND_MECHANICAL_MACHINERY_DATE_OF_COMPLETION(
			String iNSTALLATION_OF_ELECTRICAL_AND_MECHANICAL_MACHINERY_DATE_OF_COMPLETION) {
		INSTALLATION_OF_ELECTRICAL_AND_MECHANICAL_MACHINERY_DATE_OF_COMPLETION = iNSTALLATION_OF_ELECTRICAL_AND_MECHANICAL_MACHINERY_DATE_OF_COMPLETION;
	}

	public String getINSTALLATION_OF_ELECTRICAL_AND_MECHANICAL_MACHINERY_DATE_OF_START() {
		return INSTALLATION_OF_ELECTRICAL_AND_MECHANICAL_MACHINERY_DATE_OF_START;
	}

	public void setINSTALLATION_OF_ELECTRICAL_AND_MECHANICAL_MACHINERY_DATE_OF_START(String iNSTALLATION_OF_ELECTRICAL_AND_MECHANICAL_MACHINERY_DATE_OF_START) {
		INSTALLATION_OF_ELECTRICAL_AND_MECHANICAL_MACHINERY_DATE_OF_START = iNSTALLATION_OF_ELECTRICAL_AND_MECHANICAL_MACHINERY_DATE_OF_START;
	}

	public String getINSTALLATION_OF_ELECTRICAL_AND_MECHANICAL_MACHINERY_STATUS() {
		return INSTALLATION_OF_ELECTRICAL_AND_MECHANICAL_MACHINERY_STATUS;
	}

	public void setINSTALLATION_OF_ELECTRICAL_AND_MECHANICAL_MACHINERY_STATUS(String iNSTALLATION_OF_ELECTRICAL_AND_MECHANICAL_MACHINERY_STATUS) {
		INSTALLATION_OF_ELECTRICAL_AND_MECHANICAL_MACHINERY_STATUS = iNSTALLATION_OF_ELECTRICAL_AND_MECHANICAL_MACHINERY_STATUS;
	}

	public String getSCHEME_ID() {
		return SCHEME_ID;
	}

	public void setSCHEME_ID(String sCHEME_ID) {
		SCHEME_ID = sCHEME_ID;
	}

}
